#functions for ret columns from dat files generated by FLASH
#or constructed from chk/plt files

import sys
import numpy as np

#FLASHdat_retrieve(filename, column): 
#takes the path to .dat file and name of column to be retieved
#if column is a string; searches for column name in header - throws error if not in header
#if column is an integer; retrieves that column 
#loops through file, constructing array of values from that column
#returns array of values in column 

def FLASHdat_retrieve(filename, column):
	datfile = open(filename, 'r')
	header = datfile.readline().split()
	header[0] = header[0][1:]
	if isinstance(column, str):  
		if column not in header:
			print('that is not a column I know of!')
			sys.exit(column+' is not a valid column in '+filename)
		else: 
			columnIndex = header.index(column)
	elif isinstance(column, int):
		columnIndex = column
	else: 
		sys.exit('I do not know what to do with that type of column!')
	data = []
	for line in datfile:
		if line[0] != '#':
			dataRow = line.split()
			data.append(float(dataRow[columnIndex]))

	return np.array(data)


